#!/bin/sh

case "$1" in
  start)
    echo "Starting Fedora and Solr"
    su - vagrant -c "/bin/sh -c 'cd /home/vagrant/sufia-demo; nohup fcrepo_wrapper -p 8984 -i tmp > log/fedora.log 2>&1 &'"
    su - vagrant -c "/bin/sh -c 'cd /home/vagrant/sufia-demo; nohup solr_wrapper --version 6.1.0 -d solr/config/ -p 8983 -n hydra-development -i tmp/solr > log/solr.log 2>&1 &'"
    until $(curl --output /dev/null --silent --head --fail http://localhost:8983/solr); do
      printf 'waiting on Solr to start'
      sleep 1
    done
    until $(curl --output /dev/null --silent --head --fail http://localhost:8984/rest); do
      printf 'waiting on Fedora to start'
      sleep 1
    done
    echo " done"
    ;;
esac
